name: Cloud Compliance (Demo)

on:
  workflow_dispatch: {}

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r scanner/requirements.txt
      - name: Run scanner in DEMO mode
        env:
          MOCK_MODE: demo
          AWS_REGION: us-east-1
        run: python scanner/scan.py
      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: compliance-reports
          path: |
            reports/*.md
            reports/*.json
